name: Atualizar Participação de Mercado no README

on:
  schedule:
    - cron: '0 0 * * *'  # Executar todos os dias à meia-noite (UTC)
  workflow_dispatch:  # Permite disparar manualmente o fluxo

jobs:
  atualizar-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Verificar Repo
      uses: actions/checkout@v2

    - name: 2. Atualizar Porcentagem e Definir Cor
      run: |
        desktop_percentage=55
        server_percentage=35
    
        get_color() {
          if [ $1 -ge 60 ]; then
            echo "green"
          elif [ $1 -ge 30 ]; then
            echo "yellow"
          else
            echo "red"
          fi
        }
      
        desktop_color=$(get_color $desktop_percentage)
        server_color=$(get_color $server_percentage)
        readme_file="README.md"

        sed -i "s|<span style='color: *;'>$desktop_percentage%</span>|<span style='color: $desktop_color;'>$desktop_percentage%</span>|g" $readme_file
        
        sed -i "s|<span style='color: *;'>$server_percentage%</span>|<span style='color: $server_color;'>$server_percentage%</span>|g" $readme_file

    - name: 3. Commit e push das alterações
      run: |
        git config --global user.email "n3ur0cr45h"
        git config --global user.name "n3ur0cr45h"
        git add README.md
        git commit --amend --no-edit -m "Atualizando dados e cores de participação de mercado no README"
        git push --force
